export type WeiterbildungSection = {
  id: string
  navLabel: string
  title: string
  items: string[]
}

export const weiterbildungIntro =
  'Metin, içeriği değiştirilmeden konu akışına göre bölümlendirilmiştir.'

export const weiterbildungTitle = 'Weiterbildung ve İş Birliği Konsepti'

export const weiterbildungSections: WeiterbildungSection[] = [
  {
    id: 'bolum-1',
    navLabel: '1. Giriş ve Konseptin Genel Açıklaması',
    title: '1. Giriş ve Konseptin Genel Açıklaması',
    items: [
      'Merhaba Umut.',
      'Şöyle bir erkenden mesaj göndereyim dedim de sana.',
      'Daha sonra akşamüstü unutmayayım.',
      'Zaten bizimkisi de yılan hikayesine dönüştü.',
      'Bugün, yarın görüşeceğiz diye.',
      'Şimdi zaten konsept çok basit.',
      'Biraz bahsetmiştim.',
      'Ben senin web siteni görmüştüm.',
      "Orada Almanya'dan gelen Türk arkadaşlara yardımcı olduğunu gördüm web sitesinde.",
      'Bunlar yeni gelenler olsun, birkaç seneden beri orada yaşayanlar olsun vs.',
      'Şimdi bizim, benim konseptime uyan bölüm ise şu:',
      'Bu arkadaşların arasında gerek job center, gerek agentür ve arbayta kayıtlı olanlar varsa yani işsiz olanlar varsa,',
      'şu anda yaptıkları işten memnun değillerse ve onu değiştirmek istiyorlarsa,',
      'başka yeni bir şey öğrenmek istiyorlarsa biz ona "Vitabiner" diyoruz biliyorsun.',
      'onu Job Center veya Agentur für Arbeit üzerinden yapabiliyorlar.',
      'Hem de bedava yapabiliyorlar.',
      'Yani yeni bir şey öğreniyorlar, yeni bir meslek öğreniyorlar vs.',
      'Bunu bedavaya yapabiliyorlar.',
    ],
  },
  {
    id: 'bolum-2',
    navLabel: '2. Gutschein Şartı',
    title: '2. Vermittlungsgutschein veya Bildungsgutschein Şartı',
    items: [
      "Tabi bunun karşılığında Job Center'dan o Zahberberte dediğimiz kişiden Vermittungsgutschein veya Bildungsgutschein almak şartıyla eğer bunu alırlarsa o zaman buraya katılmaya hak kazanıyorlar.",
      'Benim bu konuda çalıştığım değişik firmalar var.',
      'Bir tanesinde böyle bir Vita Bildung 4 ila 6-7 hafta arasında sürebiliyor.',
      'Burada tabii ki yeni bir meslek öğrenmek, öğrenmenin dışında bir de ona yani firmalara nasıl yazışma yaparsın, nasıl şey gönderirsin, beraber gönderirsin falan vesaire nasıl daha etkili bir şekilde bunu yaparsın, bunu da gösteriyorlar.',
      'Aynı zamanda da iş bulma konusunda bir miktar yardımcı olabiliyorlar.',
    ],
  },
  {
    id: 'bolum-3',
    navLabel: '3. Kendi İşini Kurma Desteği',
    title: '3. Kendi İşini Kurmak İsteyenlere Sağlanan Destek',
    items: [
      'Onun dışında bir de kendini SEP işlemlik yapmak isteyen yani kendi iş yerini açmak isteyen arkadaşlara da yardımcı olunabiliyor.',
      "Bunun için yine Job Center'dan bir Vermittus kurşun alınıyor SEP işlemlik üzerine.",
      'Bu SEP işlemlik yapacak arkadaşlar yalnız şunu da yapmak zorundalar.',
      "Bu şeyin içerisinde, Vita Bill'in içerisinde.",
    ],
  },
  {
    id: 'bolum-4',
    navLabel: '4. Yeni Bir Meslek Öğrenmek',
    title: '4. Birinci Seçenek: Yeni Bir Meslek Öğrenmek',
    items: [
      'Şimdi birincisini anlattım.',
      'Birincisi meslek yapmak üzerine.',
      'Yani bu bulunduğu meslekten sağlık sorunları, psikolojik nedenler vesaire ötürü bunu yapmak istemeyen, meslek değiştirmek isteyen arkadaşlar başka bir meslek öğrenebiliyor.',
      'Bu bir.',
    ],
  },
  {
    id: 'bolum-5',
    navLabel: '5. Kendi İşini Kurmak',
    title: '5. İkinci Seçenek: Kendi İşini Kurmak',
    items: [
      'İkincisi kendi işini yapmak isteyen arkadaşlar yani sahip işlemek olmak isteyen arkadaşlar.',
      'Bunlar da ilk etapta Job Center veya Agentur für Arbeitten o feminist kuşağını aldıktan sonra bu Bu firmalarda başladıklarında biz onlara billiustere gidiyoruz.',
      'Burada başladıklarında ilk önce bir business plan yapmayı öğreniyorlar.',
      'Finance plan yapmayı öğreniyorlar.',
      'Ondan sonra onun akabinde onların yapacağı işin tutarlı olup olmadığına o firma karar veriyor.',
      "Yani o White Abbey'in yaptıkları firma karar veriyor.",
      "Onun akabinde de eğer track face guide dediğimiz o yazılı belgeyi yani bu iş yürür ve bu kişi bu işi yapabilir adlı belgeyi alabilirse o zaman bunu alıp tekrar job center'a ve agent de fabrika götürüyor.",
      'Bu her ikisinden birisi de nereye kayıtlıysa onlara bu konuda nasıl söyleyeyim, maddi olanaklar sağlıyor.',
    ],
  },
  {
    id: 'bolum-6',
    navLabel: '6. Çilingircilik Örneği',
    title: '6. Çilingircilik Üzerinden Verilen Kişisel Örnek',
    items: [
      'Mesela diyelim ki, mesela ben kendimden örnek vereyim istersen.',
      'Ben 15 sene önce böyle bir şey yapmıştım.',
      'O zamanlar bir senenin üstünde işsizdim.',
      'Bir tanıdığım bir arkadaş vardı, uzun süre görüşmediğim birkaç sene.',
      'Sonra bir gün böyle, benim o zamanki eşim, eski eşim, kapıyı çekerken, dış kapıyı, anahtarı içeride unutmuş.',
      'Neyse, çilingirci çağırdık.',
      "Ondan sonra Amel'le şu üstü de istiyorlar biliyorsun.",
      'Çilingirci geldi ama kim geldi?',
      'Benim o arkadaş geldi.',
      'Ben de şaşırdım.',
      'O da şaşırdı falan.',
      'Nasıl oldu diye böyle.',
      'Ondan sonra ben o kapıyı açtıktan sonra ben tabii ki biraz konuyla ilgilendiğim için sordum.',
      'Ya bu nedir?',
      'Ne yapıyorsun?',
      'Ne kadar kazanıyorsun?',
      'Dedi ya ben bir seneden beri bu işi yapıyorum dedi içine gireceğim dedi vesaire peki nasıl oldu falan ben dedi arbaşsatma üzerinden yaptım dedi tamam güzel şu anda ben de arbaşsatmayım tabii bana işin detaylarını falan anlattı biraz biraz da gösterdi nasıl yapıldığını falan gösterdi bu iş için sana ausbildung yani meslek lazım değil dedi eğer senin El becerim varsa bunu yapabiliyorsan bir türlü bir yerde kursta mursta veya benim gibi arkadaşların öğrendiysem bunu yapabilirsin dedi.',
      'O da çok güzel.',
    ],
  },
  {
    id: 'bolum-7',
    navLabel: '7. Job Center Başvurusu',
    title: '7. Job Center’a Başvuru Süreci',
    items: [
      "Neyse ben Arbastelant'a gittim.",
      'Dedim ben çilingircilik yapmak istiyorum dedim.',
      'Sayfıştanlık olarak falan.',
      "Zahper Bart'ı önce bir şaşırdı tabii ama ondan sonra dedi bu konuda bana nasıl bir referans verebilirsin dedi.",
      'Benim mesleğim otelcilikti aslında.',
      "Otelcilik mesleği öğrenmiştim Almanya'da.",
      "Ama babam marangozdu Türkiye'den.",
      'Dedem marangoz, bizim ailem marangoz.',
      'Dedim işte böyle benim babam marangozdur, dedem marangozdur, ben de biraz öğrenmişimdir, el yatkınlığım vardır falan diye.',
      'Neyse bana bir şekilde feminist kutuşağını verdi.',
      'Ben bu feminist kutuşağını işte o bildiğimiz yere gittim.',
      'Onlara bunu verdim, feminist kutuşağını.',
      'O şaynı onlara veriyorsun.',
      'O zaman onlar diyor ki tamam sen o zaman burada, sebep işlemli şikayet üzerine yapmak istediğin konu üzerine bizden 6 hafta boyunca, o zamanlar biraz daha uzundu, benim yaptığım zamanlar 15 sene önce.',
      '2 ay üzerinden gidiyorduk biz ama şu anda kısaldı.',
      'Şu anda mesela 5-6 haftada bitirebiliyorsun bunu.',
    ],
  },
  {
    id: 'bolum-8',
    navLabel: '8. Business ve Finance Plan',
    title: '8. Business Plan ve Finance Plan Eğitimi',
    items: [
      'Neyse orada işte sana kendi işlerini açacağın için business plan nasıl yapılır, nelere dikkat etmek gerekir, finance plan nasıl yapılır, nelere dikkat etmek gerekir.',
      'Ondan sonra bir de o altı hafta içerisinde sana bazı testler veriyorlar, şunu yapıyorlar, bunu yapıyorlar.',
      'Altı hafta sonunda senden bizzat kendin business planı hazırlamanı, finans planı hazırlamanı istiyorlar.',
      'Bunun içerisinde tabi çok detay var.',
      'Yani reklam nasıl yapılır falan da tut, müşteriye nasıl davranılır falan hepsi bunlar içerisinde.',
      'Ondan sonra sana sonunda diyorlar ki tamam sen testi geçtin Senin seçtiğin bu konuda şu anda burada yani çalışmak istediğin alan bu şehirde, şurada, burada mümkündür.',
      'Çok fazla konkurense yani ne bileyim yarış, seninle yarış halinde olan firma çok fazla yok falan dedikten sonra sana o track, fish, kite, beşerliğinin veriyorlar.',
    ],
  },
  {
    id: 'bolum-9',
    navLabel: '9. Maddi Destekler',
    title: '9. Başlangıç Sermayesi ve Maddi Destekler',
    items: [
      'Sana onunla gidiyorsun.',
      "Dediğim gibi job center'a veya neredeyse kayıtlıyorsan, gönül tufağı, abart.",
      'Orada mesela sana soruyorlar ki tamam sen bu işe başlarken ne kadar para ihtiyacım var?',
      'Sen de diyorsun ki işte ne bileyim bu materyaller lazım, şu lazım, bu lazım.',
      'Bana bir 5000 Euro lazım.',
      'Tamam diyorlar sana bu parayı göndereceğiz.',
      'Ama sen her bunları satın aldığında bize işte satın alma belgesini göndermen lazım.',
      'Tamam güzel.',
      'Ve bunun yanında aylık olarak hala sana desteklerini veriyorlar.',
      'Yani ne bileyim kira yardımın olsun, şu olsun, bu olsun.',
      'Bir altı ay onu devam ediyorlar.',
      'Yani konsept bu şekilde ilerliyor.',
    ],
  },
  {
    id: 'bolum-10',
    navLabel: '10. İş Bulma ve Başvuru Desteği',
    title: '10. Eğitim Sonrası İş Bulma ve Başvuru Desteği',
    items: [
      'Sahip işlenmek olursan, meslek yaparsan, birinci bölümde anlatmıştım zaten.',
      'Sen altı, yedi hafta içerisinde mesleğini yapıyorsun.',
      'Ondan sonra Dediğim gibi sana bir miktar belki iş bulma konusunda yardımcı olabilirler ama zaten sen yeni bir meslek yaptığın için firmalara, yazışmalarına falan yapıyorsun.',
      'O yazışma konusunda işte Beberbunk, Bebanskreis 5 dediğimiz olaylarda da zaten sana en baştan yardımcı oluyorlar.',
      'Sana bunları bu şekilde detaylı anlatıyorum ki yani şu anda kafanda belki o şekilde tanıdığın insanlar vardır, çalışmıyorlardır, işte ne bileyim mesleklerine hoşnut değillerdir falan.',
      'Neyi nasıl detaylı bir şekilde nasıl yapabilirleri anlatmak istiyorum.',
      'Yani sana sorarlarsa ya bu işin arka planı nedir?',
      'Sen de onları bu şekilde anlatabilirsin diyorum.',
    ],
  },
  {
    id: 'bolum-11',
    navLabel: '11. Vermittlungsgutschein',
    title: '11. Vermittlungsgutschein ile Yapılabilen Programlar',
    items: [
      'Başka bir yöntem daha var.',
      'Şimdi bu anlattığım yöntem, Famittus Gutschein içindi.',
      'Bu Famittus Gutschein ile bunları yapabiliyorsun 6-7 hafta içerisinde, takriben.',
    ],
  },
  {
    id: 'bolum-12',
    navLabel: '12. Cyber Security Eğitimi',
    title: '12. Bildungsgutschein ve Cyber Security Eğitimi',
    items: [
      'Şimdi bir de Billus Gutschein diye bir şey var.',
      'Bu biraz daha kapsamlı.',
      'Mesela şu anda benim elimde Cyber Security diye bir VitaBulum var.',
      "Sadece bunu bir firma sunuyor Almanya'da.",
      'Ve Almanya çapında da bu dalda çok fazla insan aranıyor şu anda.',
      'çalışmak için ve parası da çok güzel yani.',
      "White Abilene'den sonra.",
      'Bu en az 6 ay en fazla da 12 veya 15 ay süren bir White Abilene.',
      'Burada Cyber Security zaten düşünebilirsiniz neler olduğunu.',
      'Yani İnternet alanında internetle güvenlik alanıyla ilgili konularda işte bu arkadaşlar eğitim alıyorlar.',
    ],
  },
  {
    id: 'bolum-13',
    navLabel: '13. Ön Koşullar',
    title: '13. Cyber Security Eğitiminin Ön Koşulları',
    items: [
      'Tabi IT bilgisi olması lazım biraz bunların yani hiç IT bilgisi olmadan da buraya girmek pek akıl işi değil.',
      'Bir miktar bilmeleri lazım.',
      'En azından yani network nedir ne bileyim işte yani Böyle normal bilgisayar kullanması falan.',
      'Bunlardan biraz anlaması lazım bu kişilerin.',
      'Bunu yapmak isteyenlerin.',
    ],
  },
  {
    id: 'bolum-14',
    navLabel: '14. Modüller ve Eğitmenler',
    title: '14. Modüller ve Eğitmenler',
    items: [
      'Orada da mesela iki modül.',
      'Yani orada modüller var.',
      'Bir modül var.',
      'Onun yanına bir modül daha ekleyebilirsin.',
      'Biraz kapsamlı.',
      'Yani o konuda hangi eğitimi almak istiyorsan modülleri ekleyebiliyorsun.',
      'Veya tek bir modülle kalabiliyorsun.',
      'Bu firmada istihbarat şeyleri bile ne derler ona?',
      'Devletin istihbarattan görevlendirdiği kişiler bile eğitim veriyorlar bu firmada.',
      'O yüzden çok ilginç.',
      'Gerçekten de sağlam bir emniyet mesleği bu.',
    ],
  },
  {
    id: 'bolum-15',
    navLabel: '15. Laptop Hediyesi',
    title: '15. Laptop Hediyesi ve Motivasyon Teklifi',
    items: [
      'İşte böyle bir insanların ilgisini çekmek için de şöyle bir teklif yapıyorlar mesela.',
      "İki modül alana yani iki modül öğrenmek isteyen iki modülü öğrenip bitiren VitaBildung'u bir tane laptop hediye ediyoruz falan diyorlar mesela insanları biraz böyle motive etmek için.",
      'Bu mesela Billions Goods şahane olan bir VitaBildung.',
      'Bu da çok değişik bir şey.',
      'Şu anda da çok aranan bir meslekte.',
      'O yüzden bunu da mesela ilgilenen arkadaşlar olursa IT bölümünde bunu da sunabiliriz.',
    ],
  },
  {
    id: 'bolum-16',
    navLabel: '16. İş Birliği Modeli',
    title: '16. Olası İş Birliği Modeli',
    items: [
      'Peki yani bizim çalışmamız bu konuda nasıl olabilir?',
      'İşte sen böyle işsiz olup gerek Job Center\'da gerek Agentur ve Arbeit\'ta işsiz olup yeni bir meslek öğrenmek isteyen, kendini self-staging yapmak isteyen veya daha kapsamlı bir "Billong" dediğimiz işle yapmak isteyen arkadaşlara bu şekilde yönlendirebilirsin.',
      'Senin çok fazla vakit harcamana gerek yok.',
      'Eğer bu kafa yapısında olan arkadaşlar varsa direkt bana yönlendirip, bir miktar anlatıp kafalarına yeterse bana yönlendirip geri kısmını ben alabilirim.',
    ],
  },
  {
    id: 'bolum-17',
    navLabel: '17. Başvuru Desteği',
    title: '17. Başvuru ve Gutschein Alma Konusunda Verilecek Destek',
    items: [
      "Arkadaşları işte Job Center'a yönlendiririm.",
      "Agentürfe Haber'te yönlendiririm.",
      'Onların o feminist kutuşağını ve bildiğiniz kutuşağını almalarını sağlayabilirim.',
      'Çünkü benim elime böyle Hazır ilmi programları falan var, yazışmalar var.',
      'Onları kendilerine veririm.',
      'Onlar zaten onu ZAHR abartılarına gönderiyorlar.',
      '%50, %60 falan kabul ediliyor.',
      'Bazen ikinci görüşmede, birinci görüşmede red olsa bile ikinci görüşmede kabul edilebiliyor.',
      "Ondan sonra arkadaşlar bu shine'ları aldıktan sonra write'e bölümlerine başlıyorlar.",
    ],
  },
  {
    id: 'bolum-18',
    navLabel: '18. Kazanç Modeli',
    title: '18. Yönlendirme Başına Kazanç Modeli',
    items: [
      "Whiteaburling'e başladıktan 4 hafta sonra da biz buradan tabii ki gelir elde ediyoruz.",
      "Şöyle diyeyim, yani senin mesela bana tavsiye edip Whiteaburling'e giden arkadaşlar, olursa sen hemen hemen hiçbir şey yapmadan kişi başına 500 euro alabiliyorsun.",
      'Yani söylediğim haftada bir kişi olursa ayda 2000 euro falan eder bir ek kazanç.',
      'Güzel bir ek kazanç olabilir senin için bu.',
      'Bu şekilde ilerleyebiliriz eğer senin ilgini çekiyorsa.',
    ],
  },
  {
    id: 'bolum-19',
    navLabel: '19. Sorular ve Görüşme',
    title: '19. Sorular ve Yeniden Görüşme Önerisi',
    items: [
      'Daha başka sorularım varsa benim şu anda pek cevaplayamadığım, tabii sorabilirsin tekrar onları cevaplayabilirim.',
      'Veya başka bir uygun zamanlar, inşallah yani, ikimizin de uygun olduğu bir zaman olursa, o zaman tekrar bir camla görüşme yaparız.',
      'O zaman tekrar bir durumu genel olarak değerlendiririz neler yapabiliriz diye.',
      'Benim anlatabileceklerim bu konuda bu kadar.',
      'Çünkü çok da fazla bir detay yok.',
    ],
  },
  {
    id: 'bolum-20',
    navLabel: '20. Hedef Kitle',
    title: '20. Hedef Kitle ve Çevredeki Kişilere Ulaşılması',
    items: [
      'Sonuçta bu şu anda işsiz olan arkadaşlara bağlı veya senin çevrene bağlı diyeyim.',
      'Ne kadar çok fazla o kişilerle haşır neşir oluyorsun bilemiyorum tabii ki.',
      "Ama yani sen bu işi yapıyorsan yani Türkiye'den gelen arkadaşlara bu şekilde yardımcı olabiliyorsan sanırım ki herhalde böyle bir 3-4 sene, 5 sene burada olup da onların aralarında işsiz olan arkadaşlar varsa onlardan mesela onlara bu bilgileri sunabiliriz.",
      'Daha sonra da yardımcı olabiliriz.',
    ],
  },
  {
    id: 'bolum-21',
    navLabel: '21. Kapanış',
    title: '21. Kapanış',
    items: [
      'Peki dediğim gibi daha sonra eğer soruların varsa sorabilirsin cevaplarım veya işte uygun zamanda tekrar görüşürüz.',
      'İnşallah bir şeyler yapabiliriz.',
      'Teşekkürler, kolay gelsin sana.',
      'İyi günler.',
    ],
  },
]
